/**
 * ELIMUmaterial - Chuka University-specific catalog.
 *
 * OFFICIAL FACULTIES, SCHOOLS & COURSES (Chuka University Academic Programmes 2026).
 * Compiled from Chuka University's May 2026 KUCCPS advert and official website
 * programme listings (chuka.ac.ke). Every Bachelor's course carries 22+ real
 * semester/year units mirroring Chuka's actual programme structure so the
 * study-materials dashboard has full unit-level coverage for CU students.
 *
 * This file is CHUKA-ONLY. It is injected on top of the master catalog by
 * backend/routes/catalog.js when the selected institution id is 'chuka'.
 * No other university, faculty, course, unit or logic is affected.
 */

// Unit helper — matches the shape used by the master catalog (code, name, pages).
const U = (code, name, pages = 22) => ({ code, name, pages });

// ---------- Chuka Faculties & Schools (Official 2026) ----------
const chukaFaculties = [
  { id: 'chuka-fac-agri',   name: 'Faculty of Agriculture' },
  { id: 'chuka-fac-biz',    name: 'Faculty of Business Studies' },
  { id: 'chuka-fac-edu',    name: 'Faculty of Education and Resources Development' },
  { id: 'chuka-fac-eng',    name: 'Faculty of Engineering' },
  { id: 'chuka-fac-env',    name: 'Faculty of Environmental Studies & Resource Development' },
  { id: 'chuka-fac-hum',    name: 'Faculty of Humanities & Social Sciences' },
  { id: 'chuka-fac-sci',    name: 'Faculty of Science & Technology' },
  { id: 'chuka-sch-nur',    name: 'School of Nursing and Public Health' },
  { id: 'chuka-sch-law',    name: 'School of Law' }
];

// ---------- Chuka Courses ----------
// Every Bachelor's programme has 22+ units. Course ids are namespaced with
// the "chuka-" prefix so they never collide with the shared course catalog.
const chukaCourses = [

  // ================= 1. FACULTY OF AGRICULTURE =================
  {
    id: 'chuka-bsc-agri', code: 'BSc-AGR', name: 'BSc Agriculture',
    facultyId: 'chuka-fac-agri', duration: '4 years',
    units: [
      U('AGR101','Introduction to Agriculture'),
      U('AGR102','General Botany'),
      U('AGR103','General Zoology for Agriculture'),
      U('AGR104','Introductory Soil Science'),
      U('AGR105','Principles of Crop Production'),
      U('AGR106','Principles of Animal Production'),
      U('AGR107','Agricultural Chemistry'),
      U('AGR108','Farm Machinery & Mechanization'),
      U('AGR201','Agronomy of Field Crops'),
      U('AGR202','Soil Fertility & Plant Nutrition'),
      U('AGR203','Crop Protection (Entomology)'),
      U('AGR204','Crop Protection (Pathology)'),
      U('AGR205','Livestock Feeds & Feeding'),
      U('AGR206','Agricultural Extension & Communication'),
      U('AGR207','Agricultural Economics'),
      U('AGR208','Farm Structures & Water Engineering'),
      U('AGR301','Horticultural Crop Production'),
      U('AGR302','Dryland Farming Systems'),
      U('AGR303','Post-Harvest Technology'),
      U('AGR304','Seed Science & Technology'),
      U('AGR305','Agroforestry & Land Use'),
      U('AGR306','Farm Management & Planning'),
      U('AGR401','Research Methods in Agriculture'),
      U('AGR402','Agribusiness & Entrepreneurship'),
      U('AGR403','Agricultural Project Planning'),
      U('AGR404','Undergraduate Research Project')
    ]
  },
  {
    id: 'chuka-bsc-ansci', code: 'BSc-AS', name: 'BSc Animal Science',
    facultyId: 'chuka-fac-agri', duration: '4 years',
    units: [
      U('ANS101','Introduction to Animal Science'),
      U('ANS102','Anatomy of Farm Animals'),
      U('ANS103','Physiology of Farm Animals'),
      U('ANS104','General Biochemistry'),
      U('ANS105','Animal Genetics'),
      U('ANS106','Livestock Nutrition Principles'),
      U('ANS107','Pasture & Range Management'),
      U('ANS108','Animal Health Fundamentals'),
      U('ANS201','Dairy Cattle Production'),
      U('ANS202','Beef Cattle Production'),
      U('ANS203','Sheep & Goat Production'),
      U('ANS204','Poultry Production'),
      U('ANS205','Pig Production'),
      U('ANS206','Rabbit & Micro-livestock Production'),
      U('ANS207','Livestock Housing & Equipment'),
      U('ANS208','Animal Breeding & Reproduction'),
      U('ANS301','Animal Products Technology'),
      U('ANS302','Meat Science & Technology'),
      U('ANS303','Dairy Products Technology'),
      U('ANS304','Livestock Marketing & Economics'),
      U('ANS305','Apiculture (Beekeeping)'),
      U('ANS306','Aquaculture Basics'),
      U('ANS401','Research Methods'),
      U('ANS402','Livestock Farm Management'),
      U('ANS403','Undergraduate Research Project')
    ]
  },
  {
    id: 'chuka-bsc-hort', code: 'BSc-HORT', name: 'BSc Horticulture',
    facultyId: 'chuka-fac-agri', duration: '4 years',
    units: [
      U('HRT101','Introduction to Horticulture'),
      U('HRT102','Plant Anatomy & Morphology'),
      U('HRT103','Horticultural Soils'),
      U('HRT104','Plant Physiology for Horticulture'),
      U('HRT105','Horticultural Nursery Practices'),
      U('HRT106','Introductory Genetics'),
      U('HRT107','Agricultural Chemistry'),
      U('HRT108','Fruit Crop Production I'),
      U('HRT201','Vegetable Crop Production')
    ]
  },
  {
    id: 'chuka-bsc-food', code: 'BSc-FST', name: 'BSc Food Science & Technology',
    facultyId: 'chuka-fac-agri', duration: '4 years',
    units: [
      U('FST101','Introduction to Food Science'),
      U('FST102','Food Chemistry I'),
      U('FST103','Food Microbiology'),
      U('FST104','Food Biochemistry'),
      U('FST105','Human Nutrition'),
      U('FST106','Food Analysis'),
      U('FST107','Food Preservation Principles'),
      U('FST108','Cereal & Legume Technology'),
      U('FST201','Meat & Poultry Technology'),
      U('FST202','Dairy Technology'),
      U('FST203','Fruit & Vegetable Technology'),
      U('FST204','Fats & Oils Technology'),
      U('FST205','Beverage Technology'),
      U('FST206','Food Engineering Unit Operations'),
      U('FST207','Food Packaging & Storage'),
      U('FST208','Food Safety, HACCP & Standards'),
      U('FST301','Food Product Development'),
      U('FST302','Sensory Evaluation of Foods'),
      U('FST303','Quality Assurance in Food Industry'),
      U('FST304','Food Plant Design & Sanitation'),
      U('FST305','Food Regulations & Consumer Protection'),
      U('FST306','Entrepreneurship in Food Industry'),
      U('FST401','Research Methods'),
      U('FST402','Undergraduate Research Project')
    ]
  },
  {
    id: 'chuka-bsc-agec', code: 'BSc-AEC', name: 'BSc Agricultural Economics',
    facultyId: 'chuka-fac-agri', duration: '4 years',
    units: [
      U('AEC101','Principles of Microeconomics'),
      U('AEC102','Principles of Macroeconomics'),
      U('AEC103','Introduction to Agriculture'),
      U('AEC104','Mathematics for Economists'),
      U('AEC105','Statistics for Economists'),
      U('AEC106','Farm Records & Accounts'),
      U('AEC107','Rural Sociology'),
      U('AEC108','Agricultural Marketing')
    ]
  },
  {
    id: 'chuka-bsc-agri-bus', code: 'BSc-ABM', name: 'BSc Agribusiness Management',
    facultyId: 'chuka-fac-agri', duration: '4 years',
    units: [
      U('ABM101','Introduction to Agribusiness'),
      U('ABM102','Principles of Management'),
      U('ABM103','Principles of Microeconomics'),
      U('ABM104','Principles of Accounting'),
      U('ABM105','Business Communication'),
      U('ABM106','Introduction to Agriculture'),
      U('ABM107','Business Mathematics'),
      U('ABM108','Business Statistics'),
      U('ABM201','Agribusiness Marketing'),
      U('ABM202','Agribusiness Finance'),
      U('ABM203','Farm Business Management'),
      U('ABM204','Agricultural Value Chains'),
      U('ABM205','Rural Development & Cooperatives'),
      U('ABM206','Human Resource Management'),
      U('ABM207','Entrepreneurship & Innovation'),
      U('ABM208','Operations Management in Agribusiness'),
      U('ABM301','Agri-Supply Chain Management'),
      U('ABM302','International Agribusiness Trade'),
      U('ABM303','Strategic Management for Agribusiness'),
      U('ABM304','Agri-Business Law & Ethics'),
      U('ABM305','Agri-Insurance & Risk Management'),
      U('ABM306','Digital Agriculture & E-commerce'),
      U('ABM401','Research Methods'),
      U('ABM402','Agribusiness Plan / Project')
    ]
  },
  {
    id: 'chuka-bsc-wildlife', code: 'BSc-WEM', name: 'BSc Wildlife Enterprise and Management',
    facultyId: 'chuka-fac-agri', duration: '4 years',
    units: [
      U('WEM101','Introduction to Wildlife Management'),
      U('WEM102','Kenyan Ecosystems'),
      U('WEM103','General Zoology'),
      U('WEM104','General Botany'),
      U('WEM105','Wildlife Ecology I'),
      U('WEM106','Ornithology'),
      U('WEM107','Mammalogy')
    ]
  },
  {
    id: 'chuka-bsc-nrm', code: 'BSc-NRM', name: 'BSc Natural Resources Management',
    facultyId: 'chuka-fac-agri', duration: '4 years',
    units: [
      U('NRM101','Introduction to Natural Resources'),
      U('NRM102','Ecology & Environment'),
      U('NRM103','General Botany'),
      U('NRM104','General Zoology'),
      U('NRM105','Soil Resources'),
      U('NRM106','Water Resources'),
      U('NRM107','Forestry Resources'),
      U('NRM108','Introduction to GIS'),
      U('NRM201','Range & Pasture Management'),
      U('NRM202','Watershed Management'),
      U('NRM203','Environmental Impact Assessment'),
      U('NRM204','Environmental Law & Policy'),
      U('NRM205','Wildlife & Protected Areas'),
      U('NRM206','Climate Change & Adaptation'),
      U('NRM207','Community Natural Resource Management'),
      U('NRM208','Renewable Energy Resources'),
      U('NRM301','Land Use Planning'),
      U('NRM302','Agroforestry Systems'),
      U('NRM303','Biodiversity Conservation'),
      U('NRM304','Remote Sensing Applications'),
      U('NRM305','Environmental Economics'),
      U('NRM306','Waste & Pollution Management'),
      U('NRM401','Research Methods'),
      U('NRM402','Undergraduate Research Project')
    ]
  },
  {
    id: 'chuka-bsc-envsci-agr', code: 'BSc-ENV', name: 'BSc Environmental Science',
    facultyId: 'chuka-fac-agri', duration: '4 years',
    units: [
      U('ENV101','Introduction to Environmental Science'),
      U('ENV102','Ecology'),
      U('ENV103','Environmental Chemistry'),
      U('ENV104','Environmental Physics'),
      U('ENV105','Introduction to Meteorology & Climatology'),
      U('ENV106','Soil Science'),
      U('ENV107','Hydrology & Water Quality'),
      U('ENV108','Environmental Microbiology'),
      U('ENV201','Environmental Pollution'),
      U('ENV202','Solid & Hazardous Waste Management'),
      U('ENV203','Air Quality & Atmospheric Pollution'),
      U('ENV204','Environmental Impact Assessment'),
      U('ENV205','Environmental Auditing'),
      U('ENV206','Environmental Law & Policy'),
      U('ENV207','Sustainable Development'),
      U('ENV208','Climate Change Science'),
      U('ENV301','Environmental Health'),
      U('ENV302','GIS & Remote Sensing for Environment'),
      U('ENV303','Environmental Economics'),
      U('ENV304','Environmental Modelling'),
      U('ENV305','Renewable Energy & Environment'),
      U('ENV306','Environmental Education & Communication'),
      U('ENV401','Research Methods'),
      U('ENV402','Undergraduate Research Project')
    ]
  },
  {
    id: 'chuka-bsc-anpt', code: 'BSc-APT', name: 'BSc Animal Products Technology',
    facultyId: 'chuka-fac-agri', duration: '4 years',
    units: [
      U('APT101','Introduction to Animal Products Technology'),
      U('APT102','Anatomy & Physiology of Farm Animals'),
      U('APT103','Food & Meat Chemistry'),
      U('APT104','Food Microbiology'),
      U('APT105','Human Nutrition'),
      U('APT106','Animal Nutrition'),
      U('APT107','Livestock Production Systems'),
      U('APT108','Introductory Biochemistry'),
      U('APT201','Meat Science & Technology'),
      U('APT202','Dairy Science & Technology'),
      U('APT203','Poultry Products Technology'),
      U('APT204','Fish Products Technology'),
      U('APT205','Hides, Skins & Leather Technology'),
      U('APT206','Animal Products Analysis'),
      U('APT207','Food Safety & HACCP'),
      U('APT208','Packaging of Animal Products'),
      U('APT301','Product Development – Animal Foods'),
      U('APT302','Slaughterhouse Design & Operations'),
      U('APT303','Marketing of Animal Products'),
      U('APT304','Sensory Evaluation'),
      U('APT305','Quality Assurance & Standards'),
      U('APT306','Entrepreneurship in Livestock Industry'),
      U('APT401','Research Methods'),
      U('APT402','Undergraduate Research Project')
    ]
  },
  {
    id: 'chuka-bsc-agrext', code: 'BSc-AEE', name: 'BSc Agricultural Education & Extension',
    facultyId: 'chuka-fac-agri', duration: '4 years',
    units: [
      U('AEE101','Introduction to Agricultural Education'),
      U('AEE102','Foundations of Education'),
      U('AEE103','Educational Psychology'),
      U('AEE104','Principles of Crop Production'),
      U('AEE105','Principles of Animal Production'),
      U('AEE106','Soil Science'),
      U('AEE107','Communication Skills for Extension'),
      U('AEE108','Rural Sociology'),
      U('AEE201','Curriculum Development in Agriculture'),
      U('AEE202','Instructional Methods in Agriculture'),
      U('AEE203','Agricultural Extension Programme Planning'),
      U('AEE204','Adult & Community Education'),
      U('AEE205','Farm Management'),
      U('AEE206','Agricultural Mechanization'),
      U('AEE207','Horticulture'),
      U('AEE208','Agroforestry'),
      U('AEE301','Educational Measurement & Evaluation'),
      U('AEE302','Educational Technology'),
      U('AEE303','Gender & Agriculture'),
      U('AEE304','Extension Research Methods'),
      U('AEE305','Teaching Practice I'),
      U('AEE306','Teaching Practice II'),
      U('AEE401','Research Methods'),
      U('AEE402','Undergraduate Research Project')
    ]
  },
  {
    id: 'chuka-bsc-cpm', code: 'BSc-CPM', name: 'BSc Crop Production and Management',
    facultyId: 'chuka-fac-agri', duration: '4 years',
    units: [
      U('CPM101','Introduction to Crop Production'),
      U('CPM102','General Botany'),
      U('CPM103','Plant Physiology'),
      U('CPM104','Soil Science'),
      U('CPM105','Agricultural Chemistry'),
      U('CPM106','Introductory Genetics'),
      U('CPM107','Farm Machinery'),
      U('CPM108','Agroecology'),
      U('CPM201','Cereal Crop Production'),
      U('CPM202','Legume Crop Production'),
      U('CPM203','Root & Tuber Crop Production'),
      U('CPM204','Horticultural Crop Production'),
      U('CPM205','Industrial Crop Production'),
      U('CPM206','Weed Science'),
      U('CPM207','Crop Pest Management'),
      U('CPM208','Crop Disease Management'),
      U('CPM301','Seed Production Technology'),
      U('CPM302','Irrigation Agronomy'),
      U('CPM303','Post-Harvest Technology'),
      U('CPM304','Crop Breeding'),
      U('CPM305','Farm Business Management'),
      U('CPM306','Precision Agriculture'),
      U('CPM401','Research Methods'),
      U('CPM402','Undergraduate Research Project')
    ]
  },
  {
    id: 'chuka-bsc-olh', code: 'BSc-OLH', name: 'BSc Ornamental and Landscape Horticulture',
    facultyId: 'chuka-fac-agri', duration: '4 years',
    units: [
      U('OLH101','Introduction to Ornamental Horticulture'),
      U('OLH102','Plant Identification & Taxonomy'),
      U('OLH103','Soils for Landscape Plants'),
      U('OLH104','Plant Physiology'),
      U('OLH105','Nursery Production of Ornamentals'),
      U('OLH106','Landscape Drawing & Graphics'),
      U('OLH107','Floriculture I'),
      U('OLH108','Turfgrass Science'),
      U('OLH201','Landscape Design Principles'),
      U('OLH202','Landscape Construction'),
      U('OLH203','Interior Plantscaping'),
      U('OLH204','Arboriculture'),
      U('OLH205','Floriculture II (Cut Flowers)'),
      U('OLH206','Greenhouse Production'),
      U('OLH207','Irrigation for Landscapes'),
      U('OLH208','Landscape Pest & Disease Management'),
      U('OLH301','Urban Horticulture'),
      U('OLH302','Landscape Maintenance & Management'),
      U('OLH303','Floral Design & Decoration'),
      U('OLH304','Landscape Business & Marketing'),
      U('OLH305','Sustainable & Eco-Landscaping'),
      U('OLH306','Herbs & Aromatic Plants'),
      U('OLH401','Research Methods'),
      U('OLH402','Landscape Project & Portfolio')
    ]
  },
  {
    id: 'chuka-bsc-ahm', code: 'BSc-AHM', name: 'BSc in Animal Health Management',
    facultyId: 'chuka-fac-agri', duration: '4 years',
    units: [
      U('AHM101','Introduction to Animal Health'),
      U('AHM102','Animal Anatomy'),
      U('AHM103','Animal Physiology'),
      U('AHM104','Veterinary Microbiology'),
      U('AHM105','Veterinary Parasitology'),
      U('AHM106','Animal Nutrition & Health'),
      U('AHM107','Veterinary Pharmacology'),
      U('AHM108','Animal Behaviour & Welfare'),
      U('AHM201','Livestock Diseases I'),
      U('AHM202','Livestock Diseases II'),
      U('AHM203','Poultry Health & Diseases'),
      U('AHM204','Veterinary Public Health'),
      U('AHM205','Meat Hygiene & Inspection'),
      U('AHM206','Zoonotic Diseases'),
      U('AHM207','Animal Reproduction & AI'),
      U('AHM208','Veterinary Epidemiology'),
      U('AHM301','Herd Health Management'),
      U('AHM302','Veterinary Clinical Skills'),
      U('AHM303','Veterinary Diagnostic Techniques'),
      U('AHM304','One Health Concepts'),
      U('AHM305','Livestock Extension'),
      U('AHM306','Veterinary Ethics & Law'),
      U('AHM401','Research Methods'),
      U('AHM402','Undergraduate Research Project')
    ]
  },

  // ================= 2. FACULTY OF BUSINESS STUDIES =================
  {
    id: 'chuka-bcom-acc', code: 'BCom-ACC', name: 'Bachelor of Commerce (Accounting)',
    facultyId: 'chuka-fac-biz', duration: '4 years',
    units: [
      U('BAC101','Introduction to Business'),
      U('BAC102','Principles of Accounting I'),
      U('BAC103','Principles of Accounting II'),
      U('BAC104','Business Mathematics'),
      U('BAC105','Business Statistics'),
      U('BAC106','Principles of Microeconomics'),
      U('BAC107','Principles of Macroeconomics'),
      U('BAC108','Business Communication'),
      U('BAC201','Financial Accounting I'),
      U('BAC202','Financial Accounting II'),
      U('BAC203','Cost Accounting'),
      U('BAC204','Management Accounting'),
      U('BAC205','Taxation I'),
      U('BAC206','Auditing I'),
      U('BAC207','Company Law'),
      U('BAC208','Business Law'),
      U('BAC301','Advanced Financial Accounting'),
      U('BAC302','Taxation II'),
      U('BAC303','Auditing II'),
      U('BAC304','Corporate Finance'),
      U('BAC305','Public Sector Accounting'),
      U('BAC306','Forensic Accounting'),
      U('BAC307','Financial Reporting Standards (IFRS)'),
      U('BAC401','Strategic Management'),
      U('BAC402','Research Methods'),
      U('BAC403','Research Project')
    ]
  },
  {
    id: 'chuka-bcom-fin', code: 'BCom-FIN', name: 'Bachelor of Commerce (Banking & Finance)',
    facultyId: 'chuka-fac-biz', duration: '4 years',
    units: [
      U('BFN101','Introduction to Business'),
      U('BFN102','Principles of Accounting I'),
      U('BFN103','Principles of Accounting II'),
      U('BFN104','Business Mathematics'),
      U('BFN105','Business Statistics'),
      U('BFN106','Microeconomics'),
      U('BFN107','Macroeconomics'),
      U('BFN108','Business Communication'),
      U('BFN201','Financial Institutions & Markets'),
      U('BFN202','Corporate Finance'),
      U('BFN203','Principles of Banking'),
      U('BFN204','Bank Lending & Credit'),
      U('BFN205','International Finance'),
      U('BFN206','Investment Analysis'),
      U('BFN207','Financial Management'),
      U('BFN208','Money & Banking'),
      U('BFN301','Islamic Banking & Finance'),
      U('BFN302','Insurance & Risk Management'),
      U('BFN303','Portfolio Management'),
      U('BFN304','Derivatives & Financial Engineering'),
      U('BFN305','Bank Marketing'),
      U('BFN306','Central Banking & Monetary Policy'),
      U('BFN307','Fintech & Digital Banking'),
      U('BFN401','Strategic Management'),
      U('BFN402','Research Methods'),
      U('BFN403','Research Project')
    ]
  },
  {
    id: 'chuka-bcom-hrm', code: 'BCom-HRM', name: 'Bachelor of Commerce (Human Resource Management)',
    facultyId: 'chuka-fac-biz', duration: '4 years',
    units: [
      U('BHR101','Introduction to Business'),
      U('BHR102','Principles of Management'),
      U('BHR103','Principles of Accounting'),
      U('BHR104','Business Communication'),
      U('BHR105','Business Mathematics'),
      U('BHR106','Business Statistics'),
      U('BHR107','Microeconomics'),
      U('BHR108','Macroeconomics'),
      U('BHR201','Introduction to HRM'),
      U('BHR202','Recruitment & Selection'),
      U('BHR203','Training & Development'),
      U('BHR204','Compensation Management'),
      U('BHR205','Performance Management'),
      U('BHR206','Employee Relations'),
      U('BHR207','Labour Laws'),
      U('BHR208','Organizational Behaviour'),
      U('BHR301','Strategic HRM'),
      U('BHR302','HR Information Systems'),
      U('BHR303','International HRM'),
      U('BHR304','Occupational Health & Safety'),
      U('BHR305','Talent Management'),
      U('BHR306','Diversity & Inclusion'),
      U('BHR307','Leadership & Change Management'),
      U('BHR401','Strategic Management'),
      U('BHR402','Research Methods'),
      U('BHR403','Research Project')
    ]
  },
  {
    id: 'chuka-bcom-mkt', code: 'BCom-MKT', name: 'Bachelor of Commerce (Marketing)',
    facultyId: 'chuka-fac-biz', duration: '4 years',
    units: [
      U('BMK101','Introduction to Business'),
      U('BMK102','Principles of Marketing'),
      U('BMK103','Principles of Accounting'),
      U('BMK104','Business Communication'),
      U('BMK105','Business Mathematics'),
      U('BMK106','Business Statistics'),
      U('BMK107','Microeconomics'),
      U('BMK108','Macroeconomics')
    ]
  },
  {
    id: 'chuka-bcom-coop', code: 'BCom-COOP', name: 'Bachelor of Commerce (Cooperative Management)',
    facultyId: 'chuka-fac-biz', duration: '4 years',
    units: [
      U('BCO101','Introduction to Cooperatives'),
      U('BCO102','Principles of Management'),
      U('BCO103','Principles of Accounting'),
      U('BCO104','Business Communication'),
      U('BCO105','Business Mathematics'),
      U('BCO106','Business Statistics'),
      U('BCO107','Microeconomics'),
      U('BCO108','Macroeconomics'),
      U('BCO201','Cooperative Law & Governance'),
      U('BCO202','Cooperative Accounting'),
      U('BCO203','SACCO Management'),
      U('BCO204','Cooperative Marketing'),
      U('BCO205','Cooperative Finance'),
      U('BCO206','Rural Development'),
      U('BCO207','Cooperative Auditing'),
      U('BCO208','Human Resource in Cooperatives'),
      U('BCO301','Cooperative Business Strategy'),
      U('BCO302','ICT in Cooperatives'),
      U('BCO303','Agricultural Cooperatives'),
      U('BCO304','Consumer Cooperatives'),
      U('BCO305','Cooperative Extension'),
      U('BCO306','International Cooperative Movement'),
      U('BCO307','Cooperative Entrepreneurship'),
      U('BCO401','Strategic Management'),
      U('BCO402','Research Methods'),
      U('BCO403','Research Project')
    ]
  },
  {
    id: 'chuka-bcom-ins', code: 'BCom-INS', name: 'Bachelor of Commerce (Insurance & Risk Management)',
    facultyId: 'chuka-fac-biz', duration: '4 years',
    units: [
      U('BIN101','Introduction to Business'),
      U('BIN102','Principles of Management'),
      U('BIN103','Principles of Accounting'),
      U('BIN104','Business Communication'),
      U('BIN105','Business Mathematics'),
      U('BIN106','Business Statistics'),
      U('BIN107','Microeconomics')
    ]
  },
  {
    id: 'chuka-bcom-plm', code: 'BCom-PLM', name: 'Bachelor of Commerce (Procurement & Logistics)',
    facultyId: 'chuka-fac-biz', duration: '4 years',
    units: [
      U('BPL101','Introduction to Business'),
      U('BPL102','Principles of Management'),
      U('BPL103','Principles of Accounting'),
      U('BPL104','Business Communication'),
      U('BPL105','Business Mathematics'),
      U('BPL106','Business Statistics'),
      U('BPL107','Microeconomics'),
      U('BPL108','Macroeconomics'),
      U('BPL201','Purchasing & Supplies Management'),
      U('BPL202','Logistics Management'),
      U('BPL203','Stores & Inventory Management'),
      U('BPL204','Supply Chain Management'),
      U('BPL205','Transport Management'),
      U('BPL206','Public Procurement Law'),
      U('BPL207','Materials Management'),
      U('BPL208','Contract Management'),
      U('BPL301','International Purchasing'),
      U('BPL302','E-Procurement'),
      U('BPL303','Warehouse Management'),
      U('BPL304','Freight & Shipping'),
      U('BPL305','Green Supply Chain'),
      U('BPL306','Procurement Ethics'),
      U('BPL307','Category Management'),
      U('BPL401','Strategic Management'),
      U('BPL402','Research Methods'),
      U('BPL403','Research Project')
    ]
  },
  {
    id: 'chuka-beem', code: 'BEEM', name: 'Bachelor of Entrepreneurship & Enterprise Management',
    facultyId: 'chuka-fac-biz', duration: '4 years',
    units: [
      U('BEE101','Introduction to Entrepreneurship'),
      U('BEE102','Principles of Management'),
      U('BEE103','Principles of Accounting'),
      U('BEE104','Business Communication'),
      U('BEE105','Business Mathematics'),
      U('BEE106','Business Statistics'),
      U('BEE107','Microeconomics'),
      U('BEE108','Macroeconomics'),
      U('BEE201','Small Business Management'),
      U('BEE202','New Venture Creation'),
      U('BEE203','Enterprise Finance'),
      U('BEE204','Marketing for Entrepreneurs'),
      U('BEE205','Innovation & Creativity'),
      U('BEE206','Family Business Management'),
      U('BEE207','Business Plan Development'),
      U('BEE208','Feasibility Analysis'),
      U('BEE301','Social Entrepreneurship'),
      U('BEE302','Technology Entrepreneurship'),
      U('BEE303','International Entrepreneurship'),
      U('BEE304','Entrepreneurial Leadership'),
      U('BEE305','Franchising & Licensing'),
      U('BEE306','Enterprise Growth Strategies'),
      U('BEE307','Entrepreneurial Ethics'),
      U('BEE401','Strategic Management'),
      U('BEE402','Research Methods'),
      U('BEE403','Business Plan Project')
    ]
  },
  {
    id: 'chuka-bplm', code: 'BPLM', name: 'Bachelor of Procurement & Logistics Management',
    facultyId: 'chuka-fac-biz', duration: '4 years',
    units: [
      U('BPM101','Introduction to Procurement & Logistics'),
      U('BPM102','Principles of Management'),
      U('BPM103','Principles of Accounting'),
      U('BPM104','Business Communication'),
      U('BPM105','Business Mathematics'),
      U('BPM106','Business Statistics'),
      U('BPM107','Microeconomics'),
      U('BPM108','Macroeconomics'),
      U('BPM201','Procurement Practice'),
      U('BPM202','Logistics Systems'),
      U('BPM203','Supply Chain Strategy'),
      U('BPM204','Transport & Distribution'),
      U('BPM205','Warehouse & Inventory'),
      U('BPM206','Public Procurement Law'),
      U('BPM207','Negotiation Skills'),
      U('BPM208','Contract Management'),
      U('BPM301','Global Sourcing'),
      U('BPM302','Procurement Analytics'),
      U('BPM303','Humanitarian Logistics'),
      U('BPM304','Reverse Logistics'),
      U('BPM305','ICT in Procurement'),
      U('BPM306','Sustainable Procurement'),
      U('BPM307','Category Management'),
      U('BPM401','Strategic Management'),
      U('BPM402','Research Methods'),
      U('BPM403','Research Project')
    ]
  },
  {
    id: 'chuka-bcoop', code: 'BCoop', name: 'Bachelor of Cooperatives Management',
    facultyId: 'chuka-fac-biz', duration: '4 years',
    units: [
      U('BCM101','Introduction to Cooperatives'),
      U('BCM102','Principles of Management'),
      U('BCM103','Principles of Accounting'),
      U('BCM104','Business Communication'),
      U('BCM105','Business Mathematics'),
      U('BCM106','Business Statistics'),
      U('BCM107','Microeconomics'),
      U('BCM108','Macroeconomics'),
      U('BCM201','Cooperative Law & Governance'),
      U('BCM202','Cooperative Accounting'),
      U('BCM203','SACCO Management'),
      U('BCM204','Cooperative Marketing'),
      U('BCM205','Cooperative Finance'),
      U('BCM206','Rural Development'),
      U('BCM207','Cooperative Auditing'),
      U('BCM208','HR in Cooperatives'),
      U('BCM301','Agricultural Cooperatives'),
      U('BCM302','Consumer Cooperatives'),
      U('BCM303','ICT in Cooperatives'),
      U('BCM304','Cooperative Extension'),
      U('BCM305','International Cooperatives'),
      U('BCM306','Cooperative Entrepreneurship'),
      U('BCM307','Cooperative Policy'),
      U('BCM401','Strategic Management'),
      U('BCM402','Research Methods'),
      U('BCM403','Research Project')
    ]
  },

  // ================= 3. FACULTY OF EDUCATION AND RESOURCES DEVELOPMENT =================
  {
    id: 'chuka-bed-pri', code: 'BEd-PRI', name: 'Bachelor of Education (Primary)',
    facultyId: 'chuka-fac-edu', duration: '4 years',
    units: [
      U('EDP101','Foundations of Education'),
      U('EDP102','General Psychology'),
      U('EDP103','Sociology of Education'),
      U('EDP104','History of Education'),
      U('EDP105','Communication Skills'),
      U('EDP106','ICT in Education'),
      U('EDP107','English for Primary Teachers'),
      U('EDP108','Kiswahili for Primary Teachers'),
      U('EDP201','Curriculum Studies – Primary'),
      U('EDP202','Educational Psychology'),
      U('EDP203','Child Growth & Development'),
      U('EDP204','Mathematics Content & Methods'),
      U('EDP205','Science Content & Methods'),
      U('EDP206','Social Studies Content & Methods'),
      U('EDP207','Creative Arts Methods'),
      U('EDP208','Physical Education Methods'),
      U('EDP301','Guidance & Counselling'),
      U('EDP302','Special Needs Education'),
      U('EDP303','Educational Assessment'),
      U('EDP304','Instructional Media'),
      U('EDP305','Religious Education Methods'),
      U('EDP306','Teaching Practice I'),
      U('EDP307','Teaching Practice II'),
      U('EDP401','Educational Research Methods'),
      U('EDP402','Educational Management'),
      U('EDP403','Research Project')
    ]
  },
  {
    id: 'chuka-bed-arts', code: 'BEd-ARTS', name: 'Bachelor of Education (Arts)',
    facultyId: 'chuka-fac-edu', duration: '4 years',
    units: [
      U('EDA101','Foundations of Education'),
      U('EDA102','General Psychology'),
      U('EDA103','Communication Skills'),
      U('EDA104','ICT in Education'),
      U('EDA105','Introduction to Arts Teaching Subjects'),
      U('EDA106','Sociology of Education'),
      U('EDA107','History of Education'),
      U('EDA108','Philosophy of Education'),
      U('EDA201','Educational Psychology'),
      U('EDA202','Curriculum Development'),
      U('EDA203','Teaching Subject I – Content'),
      U('EDA204','Teaching Subject II – Content'),
      U('EDA205','Methods of Teaching – Subject I'),
      U('EDA206','Methods of Teaching – Subject II'),
      U('EDA207','Guidance & Counselling'),
      U('EDA208','Special Needs Education'),
      U('EDA301','Educational Assessment & Evaluation'),
      U('EDA302','Educational Management'),
      U('EDA303','Advanced Teaching Subject I'),
      U('EDA304','Advanced Teaching Subject II'),
      U('EDA305','Instructional Media & Technology'),
      U('EDA306','Micro-Teaching'),
      U('EDA307','Teaching Practice'),
      U('EDA401','Educational Research Methods'),
      U('EDA402','Comparative Education'),
      U('EDA403','Research Project')
    ]
  },
  {
    id: 'chuka-bed-sci', code: 'BEd-SCI', name: 'Bachelor of Education (Science)',
    facultyId: 'chuka-fac-edu', duration: '4 years',
    units: [
      U('EDS101','Foundations of Education'),
      U('EDS102','General Psychology'),
      U('EDS103','Communication Skills'),
      U('EDS104','ICT in Education'),
      U('EDS105','Introduction to Science Subjects'),
      U('EDS106','Sociology of Education'),
      U('EDS107','History of Education'),
      U('EDS108','Philosophy of Education'),
      U('EDS201','Educational Psychology'),
      U('EDS202','Curriculum Development'),
      U('EDS203','Teaching Subject I – Content (e.g., Biology)'),
      U('EDS204','Teaching Subject II – Content (e.g., Chemistry)'),
      U('EDS205','Methods of Teaching Science I'),
      U('EDS206','Methods of Teaching Science II'),
      U('EDS207','Guidance & Counselling'),
      U('EDS208','Special Needs Education'),
      U('EDS301','Educational Assessment'),
      U('EDS302','Educational Management'),
      U('EDS303','Advanced Teaching Subject I'),
      U('EDS304','Advanced Teaching Subject II'),
      U('EDS305','Laboratory Techniques & Safety'),
      U('EDS306','Micro-Teaching'),
      U('EDS307','Teaching Practice'),
      U('EDS401','Educational Research Methods'),
      U('EDS402','Comparative Education'),
      U('EDS403','Research Project')
    ]
  },
  {
    id: 'chuka-bed-ecd', code: 'BEd-ECD', name: 'Bachelor of Education (Early Childhood Development)',
    facultyId: 'chuka-fac-edu', duration: '4 years',
    units: [
      U('ECD101','Foundations of ECD'),
      U('ECD102','Child Growth & Development'),
      U('ECD103','Health & Nutrition in ECD'),
      U('ECD104','Communication Skills'),
      U('ECD105','ICT in ECD'),
      U('ECD106','Sociology of Education'),
      U('ECD107','Educational Psychology'),
      U('ECD108','Language Development in Children'),
      U('ECD201','ECD Curriculum')
    ]
  },

  // ================= 4. FACULTY OF ENGINEERING =================
  {
    id: 'chuka-bsc-eee', code: 'BSc-EEE', name: 'BSc Electrical & Electronics Engineering',
    facultyId: 'chuka-fac-eng', duration: '5 years',
    units: [
      U('EEE101','Engineering Mathematics I'),
      U('EEE102','Engineering Mathematics II'),
      U('EEE103','Engineering Physics'),
      U('EEE104','Engineering Chemistry'),
      U('EEE105','Engineering Drawing'),
      U('EEE106','Workshop Practice'),
      U('EEE107','Introduction to Programming'),
      U('EEE108','Circuit Theory I'),
      U('EEE201','Circuit Theory II'),
      U('EEE202','Electronics I (Analog)'),
      U('EEE203','Electronics II (Digital)'),
      U('EEE204','Electromagnetic Field Theory'),
      U('EEE205','Signals & Systems'),
      U('EEE206','Electrical Machines I'),
      U('EEE207','Measurements & Instrumentation'),
      U('EEE208','Microprocessors & Microcontrollers'),
      U('EEE301','Electrical Machines II'),
      U('EEE302','Power Systems Analysis'),
      U('EEE303','Control Systems'),
      U('EEE304','Communication Systems'),
      U('EEE305','Power Electronics'),
      U('EEE306','Digital Signal Processing'),
      U('EEE307','VLSI Design'),
      U('EEE401','Renewable Energy Systems'),
      U('EEE402','Industrial Attachment'),
      U('EEE501','Engineering Project I'),
      U('EEE502','Engineering Project II')
    ]
  },
  {
    id: 'chuka-bsc-aero', code: 'BSc-AERO', name: 'BSc Aeronautical Engineering',
    facultyId: 'chuka-fac-eng', duration: '5 years',
    units: [
      U('AER101','Engineering Mathematics I'),
      U('AER102','Engineering Mathematics II'),
      U('AER103','Engineering Physics'),
      U('AER104','Engineering Chemistry'),
      U('AER105','Engineering Drawing'),
      U('AER106','Workshop Practice'),
      U('AER107','Introduction to Aeronautics'),
      U('AER108','Mechanics of Materials'),
      U('AER201','Fluid Mechanics'),
      U('AER202','Thermodynamics'),
      U('AER203','Aerodynamics I'),
      U('AER204','Aircraft Structures'),
      U('AER205','Aircraft Propulsion'),
      U('AER206','Aircraft Materials'),
      U('AER207','Avionics I'),
      U('AER208','Flight Mechanics'),
      U('AER301','Aerodynamics II'),
      U('AER302','Aircraft Design I'),
      U('AER303','Control Systems'),
      U('AER304','Aircraft Maintenance'),
      U('AER305','Aviation Safety & Regulations'),
      U('AER306','Avionics II'),
      U('AER307','Airport Engineering'),
      U('AER401','UAV & Drone Technology'),
      U('AER402','Industrial Attachment'),
      U('AER501','Aeronautical Project I'),
      U('AER502','Aeronautical Project II')
    ]
  },

  // ================= 5. FACULTY OF ENVIRONMENTAL STUDIES & RESOURCE DEVELOPMENT =================
  {
    id: 'chuka-bsc-envsci', code: 'BSc-ES', name: 'BSc Environmental Science',
    facultyId: 'chuka-fac-env', duration: '4 years',
    units: [
      U('ESC101','Introduction to Environmental Science'),
      U('ESC102','General Ecology'),
      U('ESC103','Environmental Chemistry'),
      U('ESC104','Environmental Physics'),
      U('ESC105','Meteorology & Climatology'),
      U('ESC106','Soil Science'),
      U('ESC107','Water Resources'),
      U('ESC108','Environmental Microbiology'),
      U('ESC201','Pollution & Waste Management'),
      U('ESC202','Environmental Impact Assessment'),
      U('ESC203','Environmental Auditing'),
      U('ESC204','Environmental Law & Policy'),
      U('ESC205','Air Quality Management'),
      U('ESC206','Climate Change'),
      U('ESC207','Sustainable Development'),
      U('ESC208','Biodiversity Conservation'),
      U('ESC301','GIS & Remote Sensing'),
      U('ESC302','Environmental Modelling'),
      U('ESC303','Environmental Economics'),
      U('ESC304','Environmental Health'),
      U('ESC305','Renewable Energy'),
      U('ESC306','Environmental Communication'),
      U('ESC401','Research Methods'),
      U('ESC402','Undergraduate Research Project')
    ]
  },
  {
    id: 'chuka-bsc-nrm-env', code: 'BSc-NRM-E', name: 'BSc Natural Resources Management',
    facultyId: 'chuka-fac-env', duration: '4 years',
    units: [
      U('NRE101','Introduction to Natural Resources'),
      U('NRE102','Ecology'),
      U('NRE103','General Botany'),
      U('NRE104','General Zoology'),
      U('NRE105','Soil Resources'),
      U('NRE106','Water Resources'),
      U('NRE107','Forestry Resources'),
      U('NRE108','GIS Fundamentals'),
      U('NRE201','Range Management'),
      U('NRE202','Watershed Management'),
      U('NRE203','EIA & Environmental Audit'),
      U('NRE204','Environmental Law & Policy'),
      U('NRE205','Wildlife & Protected Areas'),
      U('NRE206','Climate Change & Adaptation'),
      U('NRE207','Community NRM'),
      U('NRE208','Renewable Energy'),
      U('NRE301','Land Use Planning'),
      U('NRE302','Agroforestry Systems'),
      U('NRE303','Biodiversity Conservation'),
      U('NRE304','Remote Sensing'),
      U('NRE305','Environmental Economics'),
      U('NRE306','Waste & Pollution Management'),
      U('NRE401','Research Methods'),
      U('NRE402','Research Project')
    ]
  },
  {
    id: 'chuka-bsc-wem', code: 'BSc-WEM-E', name: 'BSc Wildlife Enterprise and Management',
    facultyId: 'chuka-fac-env', duration: '4 years',
    units: [
      U('WEE101','Introduction to Wildlife Management'),
      U('WEE102','Kenyan Ecosystems'),
      U('WEE103','General Zoology'),
      U('WEE104','General Botany'),
      U('WEE105','Wildlife Ecology I'),
      U('WEE106','Ornithology'),
      U('WEE107','Mammalogy'),
      U('WEE108','Herpetology'),
      U('WEE201','Wildlife Ecology II'),
      U('WEE202','Wildlife Population Dynamics'),
      U('WEE203','Wildlife Behaviour'),
      U('WEE204','Human–Wildlife Conflict'),
      U('WEE205','Protected Area Management'),
      U('WEE206','Wildlife Policy & Law'),
      U('WEE207','Community Wildlife Conservation'),
      U('WEE208','Ecotourism Principles'),
      U('WEE301','Wildlife Enterprise Development'),
      U('WEE302','Wildlife Health & Diseases'),
      U('WEE303','Wildlife Ranching'),
      U('WEE304','GIS in Wildlife Management'),
      U('WEE305','Wildlife Marketing'),
      U('WEE306','Climate & Biodiversity'),
      U('WEE401','Research Methods'),
      U('WEE402','Research Project')
    ]
  },
  {
    id: 'chuka-bsc-tour', code: 'BSc-TOUR', name: 'BSc Tourism Management',
    facultyId: 'chuka-fac-env', duration: '4 years',
    units: [
      U('TOR101','Introduction to Tourism'),
      U('TOR102','Kenyan Tourism Resources'),
      U('TOR103','Tourism Geography'),
      U('TOR104','Principles of Management'),
      U('TOR105','Communication Skills'),
      U('TOR106','Tourism Economics'),
      U('TOR107','Introduction to Hospitality'),
      U('TOR108','Business Statistics'),
      U('TOR201','Tour Operations'),
      U('TOR202','Travel Agency Management'),
      U('TOR203','Tourism Marketing'),
      U('TOR204','Airline & Airport Operations'),
      U('TOR205','Destination Management'),
      U('TOR206','Sustainable Tourism'),
      U('TOR207','Tourism Law'),
      U('TOR208','Tourism Information Systems'),
      U('TOR301','Cultural & Heritage Tourism'),
      U('TOR302','Ecotourism'),
      U('TOR303','Event & Conference Tourism'),
      U('TOR304','Tourism Policy & Planning'),
      U('TOR305','International Tourism'),
      U('TOR306','Tourism Entrepreneurship'),
      U('TOR401','Research Methods'),
      U('TOR402','Research Project')
    ]
  },
  {
    id: 'chuka-bsc-eco', code: 'BSc-ECO', name: 'BSc Ecotourism',
    facultyId: 'chuka-fac-env', duration: '4 years',
    units: [
      U('ECO101','Introduction to Ecotourism'),
      U('ECO102','Ecology & Biodiversity'),
      U('ECO103','Protected Areas'),
      U('ECO104','Wildlife Behaviour'),
      U('ECO105','Environmental Interpretation'),
      U('ECO106','Communication Skills'),
      U('ECO107','Kenyan Ecosystems')
    ]
  },
  {
    id: 'chuka-bsc-hotel', code: 'BSc-HOT', name: 'BSc Hotel Management',
    facultyId: 'chuka-fac-env', duration: '4 years',
    units: [
      U('HOT101','Introduction to Hospitality'),
      U('HOT102','Principles of Management'),
      U('HOT103','Communication Skills'),
      U('HOT104','Front Office Operations'),
      U('HOT105','Housekeeping Operations'),
      U('HOT106','Food Production I'),
      U('HOT107','Food & Beverage Service I'),
      U('HOT108','Hospitality Accounting'),
      U('HOT201','Food Production II'),
      U('HOT202','Food & Beverage Service II'),
      U('HOT203','Accommodation Management'),
      U('HOT204','Hotel Marketing'),
      U('HOT205','Human Resource in Hospitality'),
      U('HOT206','Hotel Facilities Management'),
      U('HOT207','Hospitality Law'),
      U('HOT208','Nutrition for Hospitality'),
      U('HOT301','Bakery & Pastry'),
      U('HOT302','International Cuisine'),
      U('HOT303','Bar & Beverage Management'),
      U('HOT304','Events & Conference Management'),
      U('HOT305','Hospitality Financial Management'),
      U('HOT306','Hotel Entrepreneurship'),
      U('HOT401','Research Methods'),
      U('HOT402','Research Project')
    ]
  },

  // ================= 6. FACULTY OF HUMANITIES & SOCIAL SCIENCES =================
  {
    id: 'chuka-ba-linglit', code: 'BA-LL', name: 'BA (Linguistics & Literature)',
    facultyId: 'chuka-fac-hum', duration: '4 years',
    units: [
      U('LLT101','Introduction to Linguistics'),
      U('LLT102','Introduction to Literature'),
      U('LLT103','Communication Skills'),
      U('LLT104','Phonetics & Phonology'),
      U('LLT105','Oral Literature'),
      U('LLT106','Morphology'),
      U('LLT107','Introduction to Poetry'),
      U('LLT108','Introduction to Prose Fiction'),
      U('LLT201','Syntax'),
      U('LLT202','Semantics & Pragmatics'),
      U('LLT203','Sociolinguistics'),
      U('LLT204','African Literature'),
      U('LLT205','European Literature'),
      U('LLT206','Literary Criticism'),
      U('LLT207','Drama & Theatre'),
      U('LLT208','Discourse Analysis'),
      U('LLT301','Applied Linguistics'),
      U('LLT302','Psycholinguistics'),
      U('LLT303','Kenyan Literature'),
      U('LLT304','Comparative Literature'),
      U('LLT305','Stylistics'),
      U('LLT306','Gender & Literature'),
      U('LLT401','Research Methods'),
      U('LLT402','Research Project')
    ]
  },
  {
    id: 'chuka-ba-engling', code: 'BA-ENL', name: 'BA (English & Linguistics)',
    facultyId: 'chuka-fac-hum', duration: '4 years',
    units: [
      U('ENL101','Introduction to English Language'),
      U('ENL102','Introduction to Linguistics'),
      U('ENL103','Communication Skills'),
      U('ENL104','English Grammar'),
      U('ENL105','Phonetics & Phonology'),
      U('ENL106','Morphology'),
      U('ENL107','English Composition'),
      U('ENL108','Introduction to Literature in English'),
      U('ENL201','Syntax'),
      U('ENL202','Semantics'),
      U('ENL203','Sociolinguistics'),
      U('ENL204','History of English Language'),
      U('ENL205','English for Specific Purposes'),
      U('ENL206','Discourse Analysis'),
      U('ENL207','Pragmatics'),
      U('ENL208','Applied Linguistics'),
      U('ENL301','English Language Teaching'),
      U('ENL302','Psycholinguistics'),
      U('ENL303','Stylistics'),
      U('ENL304','Corpus Linguistics'),
      U('ENL305','English in Media'),
      U('ENL306','World Englishes'),
      U('ENL401','Research Methods'),
      U('ENL402','Research Project')
    ]
  },
  {
    id: 'chuka-ba-geoecon', code: 'BA-GE', name: 'BA (Geography & Economics)',
    facultyId: 'chuka-fac-hum', duration: '4 years',
    units: [
      U('GEE101','Introduction to Physical Geography'),
      U('GEE102','Introduction to Human Geography'),
      U('GEE103','Principles of Microeconomics'),
      U('GEE104','Principles of Macroeconomics'),
      U('GEE105','Communication Skills'),
      U('GEE106','Map Work & Cartography'),
      U('GEE107','Mathematics for Social Sciences'),
      U('GEE108','Statistics for Social Sciences'),
      U('GEE201','Geomorphology'),
      U('GEE202','Climatology'),
      U('GEE203','Population Geography'),
      U('GEE204','Economic Geography'),
      U('GEE205','Intermediate Microeconomics'),
      U('GEE206','Intermediate Macroeconomics'),
      U('GEE207','Development Economics'),
      U('GEE208','GIS & Remote Sensing'),
      U('GEE301','Urban Geography'),
      U('GEE302','Regional Development'),
      U('GEE303','Monetary Economics'),
      U('GEE304','International Trade'),
      U('GEE305','Environmental Economics'),
      U('GEE306','Econometrics'),
      U('GEE401','Research Methods'),
      U('GEE402','Research Project')
    ]
  },
  {
    id: 'chuka-ba-histecon', code: 'BA-HE', name: 'BA (History & Economics)',
    facultyId: 'chuka-fac-hum', duration: '4 years',
    units: [
      U('HEC101','Introduction to History'),
      U('HEC102','Principles of Microeconomics'),
      U('HEC103','Principles of Macroeconomics'),
      U('HEC104','African History to 1800'),
      U('HEC105','Communication Skills'),
      U('HEC106','Mathematics for Social Sciences'),
      U('HEC107','Statistics for Social Sciences'),
      U('HEC108','History of Kenya'),
      U('HEC201','World History since 1500'),
      U('HEC202','Economic History of Africa'),
      U('HEC203','Intermediate Microeconomics'),
      U('HEC204','Intermediate Macroeconomics'),
      U('HEC205','History of Ideas'),
      U('HEC206','Development Economics'),
      U('HEC207','Historiography'),
      U('HEC208','International Economic Relations'),
      U('HEC301','History of Eastern Africa'),
      U('HEC302','Political Economy'),
      U('HEC303','Public Finance'),
      U('HEC304','Contemporary World History'),
      U('HEC305','Labour Economics'),
      U('HEC306','Econometrics'),
      U('HEC401','Research Methods'),
      U('HEC402','Research Project')
    ]
  },
  {
    id: 'chuka-ba-phil', code: 'BA-PHI', name: 'BA (Philosophy)',
    facultyId: 'chuka-fac-hum', duration: '4 years',
    units: [
      U('PHI101','Introduction to Philosophy'),
      U('PHI102','Logic & Critical Thinking'),
      U('PHI103','Communication Skills'),
      U('PHI104','Ancient Philosophy'),
      U('PHI105','Ethics'),
      U('PHI106','Introduction to African Philosophy'),
      U('PHI107','Philosophy of Religion'),
      U('PHI108','Metaphysics')
    ]
  },
  {
    id: 'chuka-ba-relig', code: 'BA-REL', name: 'BA (Religious Studies)',
    facultyId: 'chuka-fac-hum', duration: '4 years',
    units: [
      U('REL101','Introduction to Religious Studies'),
      U('REL102','World Religions'),
      U('REL103','Communication Skills'),
      U('REL104','Introduction to the Bible'),
      U('REL105','African Traditional Religion'),
      U('REL106','Introduction to Islam'),
      U('REL107','Introduction to Christianity')
    ]
  },
  {
    id: 'chuka-ba-soc', code: 'BA-SOC', name: 'BA (Sociology)',
    facultyId: 'chuka-fac-hum', duration: '4 years',
    units: [
      U('SOC101','Introduction to Sociology'),
      U('SOC102','Communication Skills'),
      U('SOC103','Social Institutions'),
      U('SOC104','Introduction to Anthropology'),
      U('SOC105','Sociology of the Family'),
      U('SOC106','Introduction to Social Psychology'),
      U('SOC107','African Society'),
      U('SOC108','Sociology of Development'),
      U('SOC201','Sociological Theory I'),
      U('SOC202','Sociological Theory II'),
      U('SOC203','Research Methods I'),
      U('SOC204','Research Methods II'),
      U('SOC205','Urban Sociology'),
      U('SOC206','Rural Sociology'),
      U('SOC207','Sociology of Education'),
      U('SOC208','Sociology of Health'),
      U('SOC301','Political Sociology'),
      U('SOC302','Sociology of Gender'),
      U('SOC303','Deviance & Crime'),
      U('SOC304','Social Policy'),
      U('SOC305','Community Development'),
      U('SOC306','Population & Society'),
      U('SOC401','Advanced Research Methods'),
      U('SOC402','Research Project')
    ]
  },
  {
    id: 'chuka-ba-crim', code: 'BA-CSS', name: 'BA (Criminology & Security Studies)',
    facultyId: 'chuka-fac-hum', duration: '4 years',
    units: [
      U('CSS101','Introduction to Criminology'),
      U('CSS102','Introduction to Security Studies'),
      U('CSS103','Communication Skills'),
      U('CSS104','Introduction to Sociology'),
      U('CSS105','Introduction to Law'),
      U('CSS106','Kenyan Legal System'),
      U('CSS107','Human Rights'),
      U('CSS108','Introduction to Psychology'),
      U('CSS201','Theories of Crime'),
      U('CSS202','Juvenile Delinquency'),
      U('CSS203','Victimology'),
      U('CSS204','Policing & Society'),
      U('CSS205','Criminal Investigation'),
      U('CSS206','Forensic Science'),
      U('CSS207','Prisons & Corrections'),
      U('CSS208','Terrorism & Counter-Terrorism'),
      U('CSS301','Cybercrime'),
      U('CSS302','Organized Crime'),
      U('CSS303','Intelligence Studies'),
      U('CSS304','Conflict & Peace Studies'),
      U('CSS305','Community Policing'),
      U('CSS306','Private Security'),
      U('CSS401','Research Methods'),
      U('CSS402','Research Project')
    ]
  },
  {
    id: 'chuka-ba-comm', code: 'BA-COM', name: 'BA (Communication Studies)',
    facultyId: 'chuka-fac-hum', duration: '4 years',
    units: [
      U('COM101','Introduction to Communication'),
      U('COM102','Communication Skills'),
      U('COM103','Media & Society'),
      U('COM104','Introduction to Sociology'),
      U('COM105','Public Speaking'),
      U('COM106','Writing for Media'),
      U('COM107','Introduction to Broadcasting'),
      U('COM108','Photography Basics'),
      U('COM201','Communication Theory'),
      U('COM202','Media Law & Ethics'),
      U('COM203','News Reporting'),
      U('COM204','Feature Writing'),
      U('COM205','Radio Production'),
      U('COM206','TV Production'),
      U('COM207','Digital Media'),
      U('COM208','Advertising'),
      U('COM301','Public Relations'),
      U('COM302','Development Communication'),
      U('COM303','Media Management'),
      U('COM304','Corporate Communication'),
      U('COM305','Media Research'),
      U('COM306','Intercultural Communication'),
      U('COM401','Research Methods'),
      U('COM402','Research Project')
    ]
  },
  {
    id: 'chuka-ba-jmc', code: 'BA-JMC', name: 'BA (Journalism & Mass Communication)',
    facultyId: 'chuka-fac-hum', duration: '4 years',
    units: [
      U('JMC101','Introduction to Journalism'),
      U('JMC102','Communication Skills'),
      U('JMC103','Media History'),
      U('JMC104','News Writing'),
      U('JMC105','Introduction to Sociology'),
      U('JMC106','Photojournalism'),
      U('JMC107','Media & Society'),
      U('JMC108','Introduction to Broadcasting'),
      U('JMC201','Reporting & News Gathering'),
      U('JMC202','Editing & Sub-editing'),
      U('JMC203','Feature Writing'),
      U('JMC204','Investigative Journalism'),
      U('JMC205','Radio Journalism'),
      U('JMC206','TV Journalism'),
      U('JMC207','Media Law & Ethics'),
      U('JMC208','Online Journalism'),
      U('JMC301','Development Journalism'),
      U('JMC302','Sports Journalism'),
      U('JMC303','Business Journalism'),
      U('JMC304','Data Journalism'),
      U('JMC305','Media Management'),
      U('JMC306','International Journalism'),
      U('JMC401','Research Methods'),
      U('JMC402','Research Project')
    ]
  },
  {
    id: 'chuka-ba-kisgeo', code: 'BA-KG', name: 'BA (Kiswahili & Geography)',
    facultyId: 'chuka-fac-hum', duration: '4 years',
    units: [
      U('KGE101','Utangulizi wa Isimu ya Kiswahili'),
      U('KGE102','Introduction to Physical Geography'),
      U('KGE103','Communication Skills'),
      U('KGE104','Sarufi ya Kiswahili'),
      U('KGE105','Introduction to Human Geography'),
      U('KGE106','Fasihi Simulizi'),
      U('KGE107','Map Work'),
      U('KGE108','Mathematics for Social Sciences'),
      U('KGE201','Fonolojia ya Kiswahili')
    ]
  },
  {
    id: 'chuka-ba-mathecon', code: 'BA-ME', name: 'BA (Mathematics & Economics)',
    facultyId: 'chuka-fac-hum', duration: '4 years',
    units: [
      U('MEC101','Calculus I'),
      U('MEC102','Linear Algebra I'),
      U('MEC103','Principles of Microeconomics'),
      U('MEC104','Principles of Macroeconomics'),
      U('MEC105','Communication Skills'),
      U('MEC106','Discrete Mathematics'),
      U('MEC107','Statistics I'),
      U('MEC108','Basic Programming'),
      U('MEC201','Calculus II'),
      U('MEC202','Linear Algebra II'),
      U('MEC203','Mathematical Economics'),
      U('MEC204','Intermediate Microeconomics'),
      U('MEC205','Intermediate Macroeconomics'),
      U('MEC206','Real Analysis'),
      U('MEC207','Probability Theory'),
      U('MEC208','Optimization Techniques'),
      U('MEC301','Econometrics I'),
      U('MEC302','Econometrics II'),
      U('MEC303','Numerical Methods'),
      U('MEC304','Development Economics'),
      U('MEC305','International Economics'),
      U('MEC306','Time Series Analysis'),
      U('MEC401','Research Methods'),
      U('MEC402','Research Project')
    ]
  },
  {
    id: 'chuka-bappm', code: 'BA-PPM', name: 'Bachelor of Arts in Project Planning and Management',
    facultyId: 'chuka-fac-hum', duration: '4 years',
    units: [
      U('PPM101','Introduction to Project Management'),
      U('PPM102','Communication Skills'),
      U('PPM103','Principles of Management'),
      U('PPM104','Principles of Microeconomics'),
      U('PPM105','Introduction to Sociology'),
      U('PPM106','Business Mathematics'),
      U('PPM107','Statistics for PPM'),
      U('PPM108','Development Studies'),
      U('PPM201','Project Identification & Design'),
      U('PPM202','Project Planning Tools'),
      U('PPM203','Project Financial Management'),
      U('PPM204','Project HR Management'),
      U('PPM205','Project Procurement'),
      U('PPM206','Monitoring & Evaluation I'),
      U('PPM207','Risk Management'),
      U('PPM208','Community Development'),
      U('PPM301','Project Implementation'),
      U('PPM302','Monitoring & Evaluation II'),
      U('PPM303','Project Quality Management'),
      U('PPM304','Project Ethics'),
      U('PPM305','ICT in Project Management'),
      U('PPM306','Strategic Project Management'),
      U('PPM401','Research Methods'),
      U('PPM402','Research Project')
    ]
  },
  {
    id: 'chuka-bpsy', code: 'BPSY', name: 'Bachelor of Psychology',
    facultyId: 'chuka-fac-hum', duration: '4 years',
    units: [
      U('PSY101','Introduction to Psychology'),
      U('PSY102','Communication Skills'),
      U('PSY103','History & Systems of Psychology'),
      U('PSY104','Developmental Psychology'),
      U('PSY105','Introduction to Sociology'),
      U('PSY106','Biological Psychology'),
      U('PSY107','Statistics for Psychology'),
      U('PSY108','Introduction to Research in Psychology'),
      U('PSY201','Social Psychology'),
      U('PSY202','Cognitive Psychology'),
      U('PSY203','Personality Psychology'),
      U('PSY204','Abnormal Psychology'),
      U('PSY205','Counselling Psychology'),
      U('PSY206','Educational Psychology'),
      U('PSY207','Industrial & Organizational Psychology'),
      U('PSY208','Psychological Testing'),
      U('PSY301','Clinical Psychology'),
      U('PSY302','Health Psychology'),
      U('PSY303','Community Psychology'),
      U('PSY304','Forensic Psychology'),
      U('PSY305','Guidance & Counselling'),
      U('PSY306','Psychotherapy'),
      U('PSY401','Advanced Research Methods'),
      U('PSY402','Research Project')
    ]
  },
  {
    id: 'chuka-ba-gir', code: 'BA-GIR', name: 'Bachelor of Arts in Government and International Relations',
    facultyId: 'chuka-fac-hum', duration: '4 years',
    units: [
      U('GIR101','Introduction to Political Science'),
      U('GIR102','Communication Skills'),
      U('GIR103','Introduction to International Relations'),
      U('GIR104','Kenyan Government & Politics'),
      U('GIR105','Introduction to Sociology'),
      U('GIR106','Introduction to Public Administration'),
      U('GIR107','Political History of Africa'),
      U('GIR108','Statistics for Social Sciences'),
      U('GIR201','Political Theory I'),
      U('GIR202','Political Theory II'),
      U('GIR203','Comparative Government'),
      U('GIR204','International Political Economy'),
      U('GIR205','Diplomacy & Foreign Policy'),
      U('GIR206','International Law'),
      U('GIR207','Conflict & Peace Studies'),
      U('GIR208','International Organizations'),
      U('GIR301','African Politics'),
      U('GIR302','Global Governance'),
      U('GIR303','Democracy & Elections'),
      U('GIR304','Regional Integration'),
      U('GIR305','Human Rights'),
      U('GIR306','Security & Strategic Studies'),
      U('GIR401','Research Methods'),
      U('GIR402','Research Project')
    ]
  },

  // ================= 7. FACULTY OF SCIENCE & TECHNOLOGY =================
  {
    id: 'chuka-bsc-cs', code: 'BSc-CS', name: 'BSc Computer Science',
    facultyId: 'chuka-fac-sci', duration: '4 years',
    units: [
      U('CSC101','Introduction to Computer Science'),
      U('CSC102','Programming Fundamentals (C)'),
      U('CSC103','Discrete Mathematics'),
      U('CSC104','Calculus I'),
      U('CSC105','Communication Skills'),
      U('CSC106','Computer Organization'),
      U('CSC107','Digital Logic'),
      U('CSC108','Linear Algebra'),
      U('CSC201','Data Structures & Algorithms'),
      U('CSC202','Object Oriented Programming (Java)'),
      U('CSC203','Database Systems'),
      U('CSC204','Operating Systems'),
      U('CSC205','Computer Networks'),
      U('CSC206','Software Engineering'),
      U('CSC207','Web Programming'),
      U('CSC208','Systems Analysis & Design'),
      U('CSC301','Artificial Intelligence'),
      U('CSC302','Compiler Construction'),
      U('CSC303','Computer Graphics'),
      U('CSC304','Mobile Application Development'),
      U('CSC305','Information Security'),
      U('CSC306','Machine Learning'),
      U('CSC307','Cloud Computing'),
      U('CSC401','Research Methods'),
      U('CSC402','Research Project')
    ]
  },
  {
    id: 'chuka-bsc-acs', code: 'BSc-ACS', name: 'BSc Applied Computer Science',
    facultyId: 'chuka-fac-sci', duration: '4 years',
    units: [
      U('ACS101','Introduction to Applied Computing'),
      U('ACS102','Programming Fundamentals'),
      U('ACS103','Discrete Mathematics'),
      U('ACS104','Calculus for Computing'),
      U('ACS105','Communication Skills'),
      U('ACS106','Computer Organization'),
      U('ACS107','Digital Systems'),
      U('ACS108','Business Statistics'),
      U('ACS201','Data Structures'),
      U('ACS202','Object Oriented Programming'),
      U('ACS203','Database Systems'),
      U('ACS204','Operating Systems'),
      U('ACS205','Computer Networks'),
      U('ACS206','Software Engineering'),
      U('ACS207','Web Application Development'),
      U('ACS208','Human-Computer Interaction'),
      U('ACS301','Applied Machine Learning'),
      U('ACS302','Data Analytics'),
      U('ACS303','Mobile Development'),
      U('ACS304','IoT Systems'),
      U('ACS305','Cybersecurity'),
      U('ACS306','Cloud & DevOps'),
      U('ACS307','Multimedia Systems'),
      U('ACS401','Research Methods'),
      U('ACS402','Applied Research Project')
    ]
  },
  {
    id: 'chuka-bsc-bit', code: 'BSc-BIT', name: 'BSc Business Information Technology',
    facultyId: 'chuka-fac-sci', duration: '4 years',
    units: [
      U('BIT101','Introduction to BIT'),
      U('BIT102','Programming Fundamentals'),
      U('BIT103','Business Mathematics'),
      U('BIT104','Principles of Management'),
      U('BIT105','Principles of Accounting'),
      U('BIT106','Communication Skills'),
      U('BIT107','Business Statistics'),
      U('BIT108','Introduction to Databases'),
      U('BIT201','Object Oriented Programming'),
      U('BIT202','Systems Analysis & Design'),
      U('BIT203','Enterprise Databases'),
      U('BIT204','Business Web Development'),
      U('BIT205','Networking Essentials'),
      U('BIT206','Business Process Management'),
      U('BIT207','E-Commerce'),
      U('BIT208','Information Systems Security'),
      U('BIT301','Business Intelligence'),
      U('BIT302','Data Warehousing'),
      U('BIT303','ERP Systems'),
      U('BIT304','Mobile Business Apps'),
      U('BIT305','Cloud for Business'),
      U('BIT306','IT Project Management'),
      U('BIT307','IT Governance & Ethics'),
      U('BIT401','Research Methods'),
      U('BIT402','Research Project')
    ]
  },
  {
    id: 'chuka-bsc-bioc', code: 'BSc-BIOC', name: 'BSc Biochemistry',
    facultyId: 'chuka-fac-sci', duration: '4 years',
    units: [
      U('BIO101','General Chemistry I'),
      U('BIO102','General Chemistry II'),
      U('BIO103','General Biology'),
      U('BIO104','Calculus for Biosciences'),
      U('BIO105','Communication Skills'),
      U('BIO106','Introduction to Biochemistry'),
      U('BIO107','Cell Biology'),
      U('BIO108','Statistics for Biosciences'),
      U('BIO201','Organic Chemistry I'),
      U('BIO202','Organic Chemistry II'),
      U('BIO203','Metabolism I'),
      U('BIO204','Metabolism II'),
      U('BIO205','Molecular Biology'),
      U('BIO206','Enzymology'),
      U('BIO207','Bioenergetics'),
      U('BIO208','Microbiology for Biochemists'),
      U('BIO301','Clinical Biochemistry'),
      U('BIO302','Immunology'),
      U('BIO303','Nutritional Biochemistry'),
      U('BIO304','Genetic Engineering'),
      U('BIO305','Biochemistry Laboratory Techniques'),
      U('BIO306','Toxicology'),
      U('BIO401','Research Methods'),
      U('BIO402','Research Project')
    ]
  },
  {
    id: 'chuka-bsc-bmst', code: 'BSc-BMS', name: 'BSc Biomedical Science and Technology',
    facultyId: 'chuka-fac-sci', duration: '4 years',
    units: [
      U('BMS101','General Chemistry'),
      U('BMS102','General Biology'),
      U('BMS103','Human Anatomy'),
      U('BMS104','Human Physiology'),
      U('BMS105','Communication Skills'),
      U('BMS106','Introduction to Biomedical Sciences'),
      U('BMS107','Cell Biology'),
      U('BMS108','Biostatistics'),
      U('BMS201','Biochemistry'),
      U('BMS202','Microbiology'),
      U('BMS203','Immunology'),
      U('BMS204','Pathology'),
      U('BMS205','Parasitology'),
      U('BMS206','Molecular Biology'),
      U('BMS207','Clinical Chemistry'),
      U('BMS208','Haematology'),
      U('BMS301','Medical Genetics'),
      U('BMS302','Pharmacology Basics'),
      U('BMS303','Histopathology'),
      U('BMS304','Virology'),
      U('BMS305','Biomedical Instrumentation'),
      U('BMS306','Public Health'),
      U('BMS401','Research Methods'),
      U('BMS402','Research Project')
    ]
  },
  {
    id: 'chuka-bsc-chem', code: 'BSc-CHEM', name: 'BSc Chemistry / Industrial Chemistry',
    facultyId: 'chuka-fac-sci', duration: '4 years',
    units: [
      U('CHM101','General Chemistry I'),
      U('CHM102','General Chemistry II'),
      U('CHM103','Calculus I'),
      U('CHM104','Physics for Chemists'),
      U('CHM105','Communication Skills'),
      U('CHM106','Introduction to Analytical Chemistry'),
      U('CHM107','Chemistry Laboratory I'),
      U('CHM108','Chemistry Laboratory II'),
      U('CHM201','Inorganic Chemistry I'),
      U('CHM202','Organic Chemistry I'),
      U('CHM203','Physical Chemistry I'),
      U('CHM204','Analytical Chemistry I'),
      U('CHM205','Organic Chemistry II'),
      U('CHM206','Physical Chemistry II'),
      U('CHM207','Environmental Chemistry'),
      U('CHM208','Industrial Chemistry I'),
      U('CHM301','Instrumental Analysis'),
      U('CHM302','Spectroscopy'),
      U('CHM303','Polymer Chemistry'),
      U('CHM304','Industrial Chemistry II'),
      U('CHM305','Green Chemistry'),
      U('CHM306','Chemical Safety'),
      U('CHM401','Research Methods'),
      U('CHM402','Research Project')
    ]
  },
  {
    id: 'chuka-bsc-phys', code: 'BSc-PHY', name: 'BSc Physics',
    facultyId: 'chuka-fac-sci', duration: '4 years',
    units: [
      U('PHY101','Mechanics'),
      U('PHY102','Electricity & Magnetism'),
      U('PHY103','Calculus I'),
      U('PHY104','General Chemistry'),
      U('PHY105','Communication Skills'),
      U('PHY106','Physics Laboratory I'),
      U('PHY107','Waves & Optics'),
      U('PHY108','Modern Physics')
    ]
  },
  {
    id: 'chuka-bsc-math', code: 'BSc-MATH', name: 'BSc Mathematics / Applied Statistics / Actuarial Science',
    facultyId: 'chuka-fac-sci', duration: '4 years',
    units: [
      U('MTH101','Calculus I'),
      U('MTH102','Linear Algebra I'),
      U('MTH103','Discrete Mathematics'),
      U('MTH104','Introductory Statistics'),
      U('MTH105','Communication Skills'),
      U('MTH106','Basic Programming'),
      U('MTH107','Set Theory & Logic'),
      U('MTH108','Analytic Geometry'),
      U('MTH201','Calculus II'),
      U('MTH202','Linear Algebra II'),
      U('MTH203','Probability Theory'),
      U('MTH204','Real Analysis I'),
      U('MTH205','Ordinary Differential Equations'),
      U('MTH206','Statistical Inference'),
      U('MTH207','Complex Analysis'),
      U('MTH208','Numerical Methods'),
      U('MTH301','Applied Statistics'),
      U('MTH302','Actuarial Mathematics'),
      U('MTH303','Financial Mathematics'),
      U('MTH304','Time Series Analysis'),
      U('MTH305','Operations Research'),
      U('MTH306','Stochastic Processes'),
      U('MTH401','Research Methods'),
      U('MTH402','Research Project')
    ]
  },
  {
    id: 'chuka-bsc-bio', code: 'BSc-BIO', name: 'BSc Biology',
    facultyId: 'chuka-fac-sci', duration: '4 years',
    units: [
      U('BIL101','General Biology'),
      U('BIL102','General Botany'),
      U('BIL103','General Zoology'),
      U('BIL104','General Chemistry'),
      U('BIL105','Communication Skills'),
      U('BIL106','Introduction to Cell Biology'),
      U('BIL107','Biology Laboratory I'),
      U('BIL108','Biostatistics'),
      U('BIL201','Plant Physiology'),
      U('BIL202','Animal Physiology'),
      U('BIL203','Genetics'),
      U('BIL204','Ecology'),
      U('BIL205','Microbiology'),
      U('BIL206','Biochemistry'),
      U('BIL207','Evolution'),
      U('BIL208','Molecular Biology'),
      U('BIL301','Entomology'),
      U('BIL302','Ichthyology'),
      U('BIL303','Parasitology'),
      U('BIL304','Plant Systematics'),
      U('BIL305','Animal Systematics'),
      U('BIL306','Conservation Biology'),
      U('BIL401','Research Methods'),
      U('BIL402','Research Project')
    ]
  },
  {
    id: 'chuka-bsc-mbio', code: 'BSc-MBB', name: 'BSc Microbiology and Biotechnology',
    facultyId: 'chuka-fac-sci', duration: '4 years',
    units: [
      U('MBB101','General Chemistry'),
      U('MBB102','General Biology'),
      U('MBB103','Cell Biology'),
      U('MBB104','Calculus for Biosciences'),
      U('MBB105','Communication Skills'),
      U('MBB106','Introduction to Microbiology'),
      U('MBB107','Introduction to Biotechnology'),
      U('MBB108','Biostatistics'),
      U('MBB201','Bacteriology'),
      U('MBB202','Virology'),
      U('MBB203','Mycology'),
      U('MBB204','Parasitology'),
      U('MBB205','Molecular Biology'),
      U('MBB206','Genetic Engineering'),
      U('MBB207','Industrial Microbiology'),
      U('MBB208','Immunology'),
      U('MBB301','Food Microbiology'),
      U('MBB302','Environmental Microbiology'),
      U('MBB303','Medical Microbiology'),
      U('MBB304','Bioinformatics'),
      U('MBB305','Fermentation Technology'),
      U('MBB306','Plant Biotechnology'),
      U('MBB401','Research Methods'),
      U('MBB402','Research Project')
    ]
  },
  {
    id: 'chuka-bsc-faq', code: 'BSc-FAQ', name: 'BSc Fisheries & Aquaculture',
    facultyId: 'chuka-fac-sci', duration: '4 years',
    units: [
      U('FAQ101','Introduction to Fisheries'),
      U('FAQ102','General Zoology'),
      U('FAQ103','General Chemistry'),
      U('FAQ104','Communication Skills'),
      U('FAQ105','Ichthyology'),
      U('FAQ106','Limnology'),
      U('FAQ107','Aquatic Ecology')
    ]
  },
  {
    id: 'chuka-bsc-engphy', code: 'BSc-EPY', name: 'BSc Engineering Physics',
    facultyId: 'chuka-fac-sci', duration: '4 years',
    units: [
      U('EPY101','Mechanics'),
      U('EPY102','Electricity & Magnetism'),
      U('EPY103','Calculus I'),
      U('EPY104','Engineering Drawing'),
      U('EPY105','Communication Skills'),
      U('EPY106','Physics Laboratory I'),
      U('EPY107','Waves & Optics'),
      U('EPY108','Modern Physics'),
      U('EPY201','Thermodynamics'),
      U('EPY202','Electromagnetic Theory'),
      U('EPY203','Quantum Mechanics'),
      U('EPY204','Mathematical Physics'),
      U('EPY205','Analog Electronics'),
      U('EPY206','Digital Electronics'),
      U('EPY207','Materials Science'),
      U('EPY208','Solid State Physics'),
      U('EPY301','Microprocessors'),
      U('EPY302','Instrumentation'),
      U('EPY303','Renewable Energy'),
      U('EPY304','Signal Processing'),
      U('EPY305','Optoelectronics'),
      U('EPY306','Computational Physics'),
      U('EPY401','Research Methods'),
      U('EPY402','Engineering Physics Project')
    ]
  },
  {
    id: 'chuka-bsc-gen', code: 'BSc-GEN', name: 'BSc (General)',
    facultyId: 'chuka-fac-sci', duration: '4 years',
    units: [
      U('BSG101','General Chemistry'),
      U('BSG102','General Biology'),
      U('BSG103','Calculus I'),
      U('BSG104','Physics I'),
      U('BSG105','Communication Skills'),
      U('BSG106','Statistics I'),
      U('BSG107','Introduction to Computing'),
      U('BSG108','Science Laboratory Skills'),
      U('BSG201','Elective Science I'),
      U('BSG202','Elective Science II'),
      U('BSG203','Elective Science III'),
      U('BSG204','Elective Science IV'),
      U('BSG205','Elective Science V'),
      U('BSG206','Elective Science VI'),
      U('BSG207','Applied Mathematics'),
      U('BSG208','Environmental Science'),
      U('BSG301','Advanced Elective I'),
      U('BSG302','Advanced Elective II'),
      U('BSG303','Advanced Elective III'),
      U('BSG304','Advanced Elective IV'),
      U('BSG305','Science & Society'),
      U('BSG306','Data Analysis'),
      U('BSG401','Research Methods'),
      U('BSG402','Research Project')
    ]
  },

  // ================= 8. SCHOOL OF NURSING AND PUBLIC HEALTH =================
  {
    id: 'chuka-bsn', code: 'BScN', name: 'BSc Nursing (Basic or Upgrading)',
    facultyId: 'chuka-sch-nur', duration: '4 years',
    units: [
      U('BSN101','Human Anatomy I'),
      U('BSN102','Human Physiology I'),
      U('BSN103','Fundamentals of Nursing Practice'),
      U('BSN104','Medical Biochemistry'),
      U('BSN105','Communication Skills'),
      U('BSN106','Nursing Ethics & Professionalism'),
      U('BSN107','Microbiology & Parasitology'),
      U('BSN108','Human Anatomy II'),
      U('BSN201','Human Physiology II'),
      U('BSN202','Pharmacology'),
      U('BSN203','Medical-Surgical Nursing I'),
      U('BSN204','Medical-Surgical Nursing II'),
      U('BSN205','Community Health Nursing I'),
      U('BSN206','Maternal & Child Health Nursing'),
      U('BSN207','Mental Health Nursing'),
      U('BSN208','Paediatric Nursing'),
      U('BSN301','Critical Care Nursing'),
      U('BSN302','Nursing Management & Leadership'),
      U('BSN303','Community Health Nursing II'),
      U('BSN304','Reproductive Health'),
      U('BSN305','Nursing Informatics'),
      U('BSN306','Gerontological Nursing'),
      U('BSN307','Palliative Care'),
      U('BSN401','Research Methods'),
      U('BSN402','Research Project')
    ]
  },
  {
    id: 'chuka-bph', code: 'BPH', name: 'BSc Public Health (Pre-Service or Upgrading)',
    facultyId: 'chuka-sch-nur', duration: '4 years',
    units: [
      U('PBH101','Introduction to Public Health'),
      U('PBH102','Human Anatomy & Physiology'),
      U('PBH103','Communication Skills'),
      U('PBH104','Medical Sociology'),
      U('PBH105','Environmental Health I'),
      U('PBH106','Health Statistics'),
      U('PBH107','Health Promotion & Education'),
      U('PBH108','Nutrition & Public Health'),
      U('PBH201','Epidemiology I'),
      U('PBH202','Biostatistics'),
      U('PBH203','Communicable Diseases'),
      U('PBH204','Non-Communicable Diseases'),
      U('PBH205','Environmental Health II'),
      U('PBH206','Occupational Health & Safety'),
      U('PBH207','Maternal & Child Health'),
      U('PBH208','Health Systems Management'),
      U('PBH301','Epidemiology II'),
      U('PBH302','Global Health'),
      U('PBH303','Public Health Nutrition'),
      U('PBH304','Health Policy & Planning'),
      U('PBH305','Community Health'),
      U('PBH306','Public Health Informatics'),
      U('PBH401','Research Methods'),
      U('PBH402','Research Project')
    ]
  },
  {
    id: 'chuka-bhnd', code: 'BHND', name: 'BSc Human Nutrition and Dietetics',
    facultyId: 'chuka-sch-nur', duration: '4 years',
    units: [
      U('HND101','Introduction to Human Nutrition'),
      U('HND102','Human Anatomy & Physiology'),
      U('HND103','Food Chemistry'),
      U('HND104','Communication Skills'),
      U('HND105','Food Microbiology'),
      U('HND106','Nutritional Biochemistry'),
      U('HND107','Community Nutrition I'),
      U('HND108','Nutrition through the Life Cycle'),
      U('HND201','Clinical Dietetics I'),
      U('HND202','Clinical Dietetics II'),
      U('HND203','Food Service Management'),
      U('HND204','Community Nutrition II'),
      U('HND205','Nutrition Assessment'),
      U('HND206','Public Health Nutrition'),
      U('HND207','Food Safety & Regulations'),
      U('HND208','Nutrition Counselling'),
      U('HND301','Nutrition in Emergencies'),
      U('HND302','Sports & Fitness Nutrition'),
      U('HND303','Nutrition & Non-Communicable Diseases'),
      U('HND304','Nutrition Programmes Planning'),
      U('HND305','Food Product Development'),
      U('HND306','Nutrition Entrepreneurship'),
      U('HND401','Research Methods'),
      U('HND402','Research Project')
    ]
  },
  {
    id: 'chuka-bhrit', code: 'BHRIT', name: 'BSc Health Records and Information Technology',
    facultyId: 'chuka-sch-nur', duration: '4 years',
    units: [
      U('HRT101','Introduction to Health Records'),
      U('HRT102','Medical Terminology'),
      U('HRT103','Human Anatomy & Physiology'),
      U('HRT104','Communication Skills'),
      U('HRT105','Introduction to ICT'),
      U('HRT106','Health Information Systems I'),
      U('HRT107','Health Statistics I'),
      U('HRT108','Filing & Records Management'),
      U('HRT201','Medical Coding & Classification')
    ]
  },

  // ================= 9. SCHOOL OF LAW =================
  {
    id: 'chuka-llb', code: 'LLB', name: 'Bachelor of Laws (LLB)',
    facultyId: 'chuka-sch-law', duration: '4 years',
    units: [
      U('LLB101','Legal Systems & Methods'),
      U('LLB102','Legal Research & Writing'),
      U('LLB103','Communication Skills'),
      U('LLB104','Constitutional Law I'),
      U('LLB105','Criminal Law I'),
      U('LLB106','Law of Contract I'),
      U('LLB107','Law of Torts I'),
      U('LLB108','Introduction to Jurisprudence'),
      U('LLB201','Constitutional Law II'),
      U('LLB202','Criminal Law II'),
      U('LLB203','Law of Contract II'),
      U('LLB204','Law of Torts II'),
      U('LLB205','Law of Evidence'),
      U('LLB206','Family Law'),
      U('LLB207','Property Law I'),
      U('LLB208','Administrative Law'),
      U('LLB301','Property Law II'),
      U('LLB302','Equity & Trusts'),
      U('LLB303','Commercial Law'),
      U('LLB304','Company Law'),
      U('LLB305','Public International Law'),
      U('LLB306','Human Rights Law'),
      U('LLB307','Environmental Law'),
      U('LLB401','Labour Law'),
      U('LLB402','Alternative Dispute Resolution'),
      U('LLB403','Legal Ethics'),
      U('LLB404','Research Methods & Project')
    ]
  }
];

module.exports = { chukaFaculties, chukaCourses };
